import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen w-screen overflow-hidden">
        <div className="h-full mx-auto md:w-[50rem] py-2">
          <div className="h-full border border-gray-200 bg-gray-200 mockup-window dark:bg-base-300 dark:border-base-300 flex flex-col">
            <div className="flex justify-center">
              <input
                type="text"
                autoComplete="off"
                placeholder="开始创作你的画作吧！"
                className="input w-full max-w-xs"
              />
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
